In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from scipy.cluster import hierarchy
from scipy.spatial import distance_matrix
from matplotlib import pyplot as plt
from sklearn import manifold, datasets
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import linkage, dendrogram

In [3]:
df = pd.read_csv(r"C:\Users\DE737AP\OneDrive - EY\Documents\03. Data Science\GitHub\Machine-Learning-Projects\07. Week 7 Advanced Machine Learning - Clustering\codon_usage.csv")

C:\Users\DE737AP\AppData\Local\Temp\ipykernel_10480\709676484.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\DE737AP\OneDrive - EY\Documents\03. Data Science\GitHub\Machine-Learning-Projects\07. Week 7 Advanced Machine Learning - Clustering\codon_usage.csv")


In [4]:
df.head()

Kingdom  DNAtype  SpeciesID  Ncodons  \
0     vrl        0     100217     1995   
1     vrl        0     100220     1474   
2     vrl        0     100755     4862   
3     vrl        0     100880     1915   
4     vrl        0     100887    22831   

                               SpeciesName      UUU      UUC      UUA  \
0  Epizootic haematopoietic necrosis virus  0.01654  0.01203  0.00050   
1                         Bohle iridovirus  0.02714  0.01357  0.00068   
2             Sweet potato leaf curl virus  0.01974   0.0218  0.01357   
3             Northern cereal mosaic virus  0.01775  0.02245  0.01619   
4           Soil-borne cereal mosaic virus  0.02816  0.01371  0.00767   

       UUG      CUU  ...      CGG      AGA      AGG      GAU      GAC  \
0  0.00351  0.01203  ...  0.00451  0.01303  0.03559  0.01003  0.04612   
1  0.00678  0.00407  ...  0.00136  0.01696  0.03596  0.01221  0.04545   
2  0.01543  0.00782  ...  0.00596  0.01974  0.02489  0.03126  0.02036   
3  0.00992  0.01567  ...  0.00366  0.01410  0.01671  0.03760  0.01932   
4  0.03679  0.01380  ...  0.00604  0.01494  0.01734  0.04148  0.02483   

       GAA      GAG      UAA      UAG      UGA  
0  0.01203  0.04361  0.00251  0.00050  0.00000  
1  0.01560  0.04410  0.00271  0.00068  0.00000  
2  0.02242  0.02468  0.00391  0.00000  0.00144  
3  0.03029  0.03446  0.00261  0.00157  0.00000  
4  0.03359  0.03679  0.00000  0.00044  0.00131  

[5 rows x 69 columns]

In [26]:
## for the categorical variables check cardinality 
cat_cols = df.select_dtypes(include='object').columns
# get the number of unique values in each categorical column
for col in cat_cols:
    print(col, " - ", df[col].nunique())

Kingdom  -  11
SpeciesName  -  13016
UUU  -  6797
UUC  -  5874


In [27]:
# cardinality of the discrete numerical column 
df.DNAtype.nunique()

11

In [30]:
## cleaning up the column data types 
df['UUU'] = pd.to_numeric(df['UUU'], errors='coerce')
df['UUC'] = pd.to_numeric(df['UUC'], errors='coerce')

In [32]:
#Dropping the SpeciesID and SpeciesName column
df.drop(['SpeciesID','SpeciesName'], inplace=True, axis=1)

## Hierachical Clustering with Kingdoms as labels 

In [37]:
# Sclaing our data 
scaler = MinMaxScaler()
X = df.drop('Kingdom',axis=1)
X = scaler.fit_transform(X)

In [38]:
dist_matrix = distance_matrix(X, X)
print(dist_matrix)

[[0.         0.38928545 0.94493444 ... 1.47515749 1.22700362 1.3351641 ]
 [0.38928545 0.         0.94437158 ... 1.44787355 1.24610339 1.31150987]
 [0.94493444 0.94437158 0.         ... 1.40452914 1.17116139 1.20578005]
 ...
 [1.47515749 1.44787355 1.40452914 ... 0.         1.6178877  0.51408096]
 [1.22700362 1.24610339 1.17116139 ... 1.6178877  0.         1.32194152]
 [1.3351641  1.31150987 1.20578005 ... 0.51408096 1.32194152 0.        ]]


In [39]:
agglom = AgglomerativeClustering(n_clusters = 11, linkage = 'average')
agglom.fit(dist_matrix)
agglom.labels_

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [40]:
# Add it to our data frame to indicate which cluster a row belongs to
df['Cluster_'] = agglom.labels_
df.head()

AttributeError: 'AgglomerativeClustering' object has no attribute 'labels_'

In [41]:
#Performing hierarchical clustering
linked = linkage(X, method='ward')

ValueError: The condensed distance matrix must contain only finite values.

In [ ]:
#Creating a dendrogram
plt.figure(figsize=(15, 15))
dendrogram(linked,
           orientation='right',
           labels=df['Kingdom'].values,
           distance_sort = 'descending',
           show_leaf_counts=True)

#plt.yticks(rotation=45, ha='right', fontsize=10)
plt.title('Dendrogram with Kingdom labels')
plt.ylabel('Kingdom Labels')
plt.xlabel('Distance')
plt.show()